### ISSUE TITLE
is this mod dead?

### ISSUE THREAD

**Issue by xXFoundationXx** [jtorleon-studios-team/bettervillages#120]

**Comment by xXFoundationXx** [comment]
then curios, did something stop the production of the taiga village?

**Comment by jtorleonstudios** [comment]
The production is not stopped, the taiga village will soon be available. Thank you for your patience, and believe me, you'll love the taiga village if you like the hobbit village.

**Comment by jtorleonstudios** [comment]
![image](https://github.com/user-attachments/assets/3ec26b55-ba38-4e9f-8560-60ba0a7d5604)
hoping these will please you :)

**Comment by xXFoundationXx** [comment]
im glad to hear it, been hoping for it for so long

**Comment by vinnyg0621** [comment]
i'm hyped!
