### ISSUE TITLE
please update more villagers and bountiful compatibility

### ISSUE THREAD

**Issue by vinnyg0621** [jtorleon-studios-team/bettervillages#126]
the new spruce forest update came out, and it looks so cool! but only if you were to update the more villagers and bountiful compact datapack to newest versions of the game and the mod... 😔

**Comment by vinnyg0621** [comment]
@jtl-elisa can you please update this datapack? thanks!!

**Comment by laxlacks888** [comment]
Any update on this getting updated to 1.20.1?

**Comment by tmslpm** [comment]
#50 duplicate
