### ISSUE TITLE
Dirt spawn over village structure

### ISSUE THREAD

**Issue by Michau60** [jtorleon-studios-team/bettervillages#131]
![2024-11-24_14 47 14](https://github.com/user-attachments/assets/ccbaacda-4552-4a45-897a-077f2c551f19)
Every village that spawns has this weird placed dirt blocks over them. Are there any known incompatibilites with other mods?

**Comment by jtl-elisa** [comment]
Hi, version ? loader ?

**Comment by Michau60** [comment]
1.20.1 Forge 47.3.5

**Comment by jtl-elisa** [comment]
Ok.. weird.

I tested on forge 47.3.0 and 47.3.5 and the village is generated normally. (Of course I checked all village (taige, snowy, plain,...)

Maybe a mod modifies something in the villages, or a datapack and create this problem ?

**Comment by Michau60** [comment]
Got 3 villages that have this bug, and the other 3 spawned as it should

**Comment by Michau60** [comment]
[mods.txt](https://github.com/user-attachments/files/17894865/mods.txt)

**Comment by jtl-elisa** [comment]
How did you get the mod? in modpack ?

**Comment by TheButterbrotMan** [comment]
Could you add the latest.log as well please? Add it to: https://gist.github.com/

**Comment by Michau60** [comment]
Got from modrinth, i'm making my own modpacks

**Comment by Michau60** [comment]
https://gist.github.com/Michau60/9c436d7382d336dc2da80581f1dffe60

**Comment by Michau60** [comment]
And the server latest.log:
https://gist.github.com/Michau60/fa0f4c526dbe9c61c72037e0f4afcca2

**Comment by jtl-elisa** [comment]
Thank you for your feedback! It appears that another mod is conflicting with ours. (Unfortunately, I’m currently unable to identify which mod is causing the issue.)

We plan to implement our own namespace soon to prevent such conflicts in the future.

If you gather additional information on your side, please don’t hesitate to update the issue. This will help us investigate further and assist other users encountering the same issue.

Thank you for your patience.

**Comment by tmslpm** [comment]
This problem is not caused by our mods, it's strictly impossible from the point of view of our code, we don't currently have any functionality that could produce this.
